### PR TITLE
remove unnecessary getAlternatives method in strategies and alternati…

### PR DESCRIPTION
**Pull request by aloupfor**
…ve manager, add call to new method addAlternative, add call to new method getAlternatives from MediaInterface

https://github.com/open-orchestra/open-orchestra-media-bundle/pull/152

### CODE REVIEW

**Comment by ngilain** [comment]
:+1:

**Comment by ngilain** [comment]
:+1:

**Comment by aloupfor** [comment]
https://github.com/open-orchestra/open-orchestra-media-bundle/pull/152

**Comment by alavieille** [comment]
:+1:

**Pull request merged**
