### PR TITLE
harmonize media modal style

### PR DESCRIPTION
**Pull request by nicolasThal**
@juchi if you agree, I will also push the modification on the 1.0 branch

### CODE REVIEW

**Comment by alavieille** [comment]
:+1:

**Comment by juchi** [comment]
can you double check the tilde (~) usage, I never saw it and there's no mention of it on MDN https://developer.mozilla.org/en-US/docs/Web/CSS/calc

**Comment by nicolasThal** [comment]
I will check with @itkg-ngilain

**Comment by alavieille** [comment]
it's for conflict between less and property calc of css3 :  
http://stackoverflow.com/questions/11972084/less-aggressive-compilation-with-css3-calc

**Comment by juchi** [comment]
Ok thanks for the tip.
However, as the calculation here is valid for the CSS3 syntax, I would personally dump the less syntax to avoid misunderstanding.
:+1:

**Pull request merged**
