### PR TITLE
remove flush from loops

### PR DESCRIPTION
**Pull request by veolys-nanne**
[OO-BUGFIX] Move document manager flush out of the loops

### CODE REVIEW

**Comment by ngilain** [comment]
:+1:

**Review by pdenis — COMMENTED** [review]
To improve performance,  you have to add persisted groups as flush arguments

**Comment by ghost** [comment]
As you are in a listener, maybe you should flush only items updated by the listener to prevent flushing of items updated by main logic.

**Comment by veolys-nanne** [comment]
@pdenis : passing array of objects in flush won't increase performance. It will just secure the perimeter of that flush as said by @itkg-canne

**Comment by juchi** [comment]
Actually @pdenis is right, a flush with no argument will process all registered doctrine objects instead of just the ones you want to flush. If there has been some objects retrieved from the database during the same request this can increase processing time significantly.

**Comment by veolys-nanne** [comment]
@pdenis , @juchi : the real cost is the number of calls to documentManager flush. As the action method will  make a flush after the listener did it,  there is no difference (flushed objects are detached). To resume : flush 5 objects + flush 5 objects = flush 3 objects + flush 7 objects. No performance improvement as we do not work several times on same persisted object.

**Comment by pdenis** [comment]
:+1:

**Comment by ngilain** [comment]
:+1:

**Review by alavieille — APPROVED** [review]

**Pull request merged**
